apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
{{- .Values.failoverip1 | indent 2 -}}: {{ .Release.Namespace -}}/{{- .Values.target -}} # add your config map here. must map the base64 encoded IP in secrets.yaml
