apiVersion: v1
data:
  failover-ip: {{ .Values.failoverip1 | b64enc }}
  hetzner-token: {{ .Values.hetznertoken | b64enc }}
  hetzner-pass: {{ .Values.hetznerpass | b64enc }}
  hetzner-user: {{ .Values.hetzneruser | b64enc }}
kind: Secret
metadata:
  name: hetzner-secret-failoverip-1
type: Opaque
